version: '3'
 
services:

  mysql:
    image: mysql:9
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: database
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    ports:
      - "3306:3306"
    volumes:
      - ./backup.sql:/docker-entrypoint-initdb.d/backup.sql
#      - dbdata:/var/lib/mysql

#volumes:
#  dbdata: