server:
  port: 9090

spring:
   kafka:
     consumer:
        bootstrap-servers: kafka:9093
        group-id: mygroupid
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

topic:
  name: greeting