version: '3'

services:

  kafka:
    image: obsidiandynamics/kafka
    ports:
      - "2181:2181"
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: "INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:29092,EXTERNAL://kafka:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
    networks:
      - network

  krafdrop:
    image: obsidiandynamics/kafdrop
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:29092"
    networks:
      - network
    depends_on:
      - kafka

  producer:
    image: producer
    container_name: producer
    build:
      context: ../../springboot3-kafka-obsidiandynamics-string-config_producer
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      KAFKA_URL: kafka:29092
    networks:
      - network
    depends_on:
      - kafka
  
  consumer:
    image: consumer
    container_name: consumer
    build:
      context: ../../springboot3-kafka-obsidiandynamics-string-config_consumer
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    environment:
      KAFKA_URL: kafka:29092
    networks:
      - network
    depends_on:
      - kafka

networks:
  network:
    name: greeting-network