apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-ui
  name: kafka-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-ui
  template:
    metadata:
      labels:
        app: kafka-ui
    spec:
      containers:
        - env:
            - name: DYNAMIC_CONFIG_ENABLED
              value: "true"
            - name: KAFKA_CLUSTERS_BOOTSTRAPSERVERS
              value: kafka:9092
            - name: KAFKA_CLUSTERS_NAME
              value: local
          image: provectuslabs/kafka-ui:v0.7.2
          name: kafka-ui
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-ui
  name: kafka-ui
spec:
  ports:
    - name: "8086"
      port: 8086
      targetPort: 8080
  selector:
    app: kafka-ui