version: "3"
services:
  postgres:
    image: postgres:alpine3.17
    container_name: postgres-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: database
    #volumes:
    #  - local_pgdata:/var/lib/postgresql/data
      
  pgadmin:
    image: dpage/pgadmin4:6.20
    container_name: pgadmin_container
    links:
      - postgres
    ports:
      - "8081:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    #volumes:
    #  - pgadmin-data:/var/lib/pgadmin

#volumes:
#  local_pgdata:
#  pgadmin-data: