version: '3'

services:
  
  consumer:
    image: consumer
    container_name: consumer
    build:
      context: ./springboot-kafka-consumer
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    networks:
      - network

networks:
  network:
    name: greeting-network