# Datasource
spring:

  data:
    mongodb:
      host: localhost
      port: 27017
      database: helloworld-db
      username: mongoadmin
      password: mongoadmin
      authentication-database: admin

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:7070/realms/helloworld-realm
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
