version: '3'

services:

  eclipse-mosquitto:
    image: eclipse-mosquitto:2.0.15
    container_name: eclipse-mosquitto-container    
    ports:
      - 1883:1883
    volumes: 
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf