apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\IT\repo-private\chrisblog-it-java-springboot\arichitectures\event-driven\stream\kafka\kraft\springboot-kafka-bitnami-docker-compose\kompose-windows-amd64.exe --file .\docker-compose.yml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: producer
  name: producer
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: producer
