apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\IT\repo-private\chrisblog-it-java-springboot\arichitectures\event-driven\stream\kafka\kraft\springboot-kafka-bitnami-docker-compose\kompose-windows-amd64.exe --file .\docker-compose.yml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: producer
  name: producer
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: producer
  template:
    metadata:
      annotations:
        kompose.cmd: C:\IT\repo-private\chrisblog-it-java-springboot\arichitectures\event-driven\stream\kafka\kraft\springboot-kafka-bitnami-docker-compose\kompose-windows-amd64.exe --file .\docker-compose.yml convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: producer
    spec:
      containers:
        - image: producer
          name: producer
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
