version: "4"
services:

  mongodb:
    image: mongo:7.0.5
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: database
    volumes:
      - ./data/mongodb:/data/db

  app:
    image: app-image:0.0.1
    container_name: app-container
    build:
      context: ../../
      dockerfile: docker/Dockerfile
    environment:
      spring.data.mongodb.uri: mongodb://root:password@mongodb:27017/database?authSource=admin
    depends_on:
      mongodb:
        condition: service_started
    ports:
      - 8080:8080
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s