version: '3'
 
services:

  mysql:
    image: mysql:5.7
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_password
      MYSQL_DATABASE: database
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    ports:
      - "3306:3306"
    networks:
      - helloworld-network
#    volumes:
#      - dbdata:/var/lib/mysql

  be:
    image: be-image:0.0.1
    container_name: be-container
    build:
      context: ./fe-thymeleaf-be-springboot-db-sql-mysql_BE
      dockerfile: Dockerfile
    environment:
      spring.datasource.url: jdbc:mysql://mysql:3306/database
    ports:
      - 8081:8081
    networks:
      - helloworld-network

  fe:
    image: fe-image:0.0.1
    container_name: fe-container
    build:
      context: ./fe-thymeleaf-be-springboot-db-sql-mysql_FE
      dockerfile: Dockerfile
    environment:
      baseurl.be: http://be:8081
    ports:
      - 8080:8080
    networks:
      - helloworld-network

  networks:
    helloworld-network:
      name: helloworld-network-name