apiVersion: apps/v1
kind: Deployment
metadata:
  name: be-deployment
  labels:
    app: be-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: be-container
  template:
    metadata:
      labels:
        app: be-container
    spec:
      containers:
      - name: be-container
        image: wisniewskir/fe-thymeleaf-be-springboot-db-sql-mysql_be:0.0.1
        ports:
        - containerPort: 8081
        env:
        - name: spring.datasource.url
          value: jdbc:mysql://mysql-container:3306/database
        readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 15
        livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 15
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: service-helloworld-kubernetes
spec:
  selector:
    app: container-helloworld
  ports:
    - port: 8080
      targetPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: service-helloworld-show
spec:
  type: NodePort
  selector:
    app: container-helloworld
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30002