 services:

  localhost:
    container_name: localhost
    image: alpine:latest
    command: sleep infinity
    ports:
    - "8080:8080"
    - "9090:9090"

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:26.0
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin    
    command:
      - "start-dev"
    network_mode: "service:localhost"

  app:
    container_name: app
    image: app
    environment:
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://localhost:8080/realms/helloworld-realm
    build:
      context: ./
      dockerfile: Dockerfile
    network_mode: "service:localhost"