version: "3"
services:
  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: database
    volumes:
      - .backup.sql:/docker-entrypoint-initdb.d/backup.sql