server:
  port: 9090

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/helloworld-realm

jwt:
  auth:
    converter:
      resource-id: helloworld-client
      principle-attribute: preferred_username
