version: '3'

services:

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - network

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    expose:
    - "9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE      
    networks:
      - network

  producer1:
    image: producer1
    container_name: producer1
    build:
      context: ./springboot-kafka-producer
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: 8080
      SPRING_KAFKA_PRODUCER_BOOTSTRAP_SERVERS: kafka:9093
      SPRING_KAFKA_PRODUCER_KEY_SERIALIZER: org.apache.kafka.common.serialization.StringSerializer
      SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER: org.apache.kafka.common.serialization.StringSerializer
      TOPIC_NAME: greeting 
    networks:
      - network
    depends_on:
      - kafka

  producer2:
    image: producer2
    container_name: producer2
    build:
      context: ./springboot-kafka-producer
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      SERVER_PORT: 8081
      SPRING_KAFKA_PRODUCER_BOOTSTRAP_SERVERS: kafka:9093
      SPRING_KAFKA_PRODUCER_KEY_SERIALIZER: org.apache.kafka.common.serialization.StringSerializer
      SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER: org.apache.kafka.common.serialization.StringSerializer
      TOPIC_NAME: greeting 
    networks:
      - network
    depends_on:
      - kafka
  
  consumer:
    image: consumer
    container_name: consumer
    build:
      context: ./springboot-kafka-consumer
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    networks:
      - network
    depends_on:
      - kafka

networks:
  network:
    name: greeting-network