version: '3.8'

services:
  
  helloworld:
    image: helloworld-image
    container_name: helloworld-container
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080
  
  redis:
    image: redis:7.0.11-alpine
    container_name: redis-container
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - cache:/data

volumes:
  cache:
    driver: local  