apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: consumer
  name: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
        - image: wisniewskikr/springboot3-kafka-obsidiandynamics-json_consumer:0.0.1
          name: consumer
          ports:
            - containerPort: 9090
              protocol: TCP
          env:
            - name: SPRING_KAFKA_CONSUMER_BOOTSTRAP_SERVERS
              value: kafka:29092
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: consumer
  name: consumer
spec:
  ports:
    - name: "9090"
      port: 9090
      targetPort: 9090
  selector:
    app: consumer