version: '3.8' 
 
services:

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:26.0
    depends_on:
      - postgres
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
    command: ["start-dev", "--import-realm"]
    volumes:
      - ./realm-export.json:/opt/keycloak/data/import/realm-export.json
    ports:
      - "8080:8080"

  app:
    container_name: app
    image: app
    build:
      context: ./
      dockerfile: Dockerfile
    environment:      
      WAIT_HOSTS: keycloak:8080
      WAIT_TIMEOUT: 60
      SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUERURI: http://keycloak:8080/realms/helloworld-realm    
    ports:
      - "9090:9090"

volumes:
  postgres_data: