spring:
  application:
    name: springboot3-payment-stripe-api

stripe:
  secretKey:
  successUrl: http://localhost:8080/api/v1/success
  cancelUrl: http://localhost:8080/api/v1/cancel
  sessionDurationInSeconds: 60
