version: '3'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    container_name: elasticsearch-container
    ports:
      - 9200:9200
      - 9300:9300
    environment:
        discovery.type: single-node
        xpack.security.enabled: false
   
  kibana:
    image: docker.elastic.co/kibana/kibana:8.6.2
    container_name: kibana-container
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://localhost:9200