spring:
  security:
    oauth2:
      client:
        provider:
          okta:            
            authorization-uri: https://dev-58841934.okta.com/oauth2/default/v1/authorize
            token-uri: https://dev-58841934.okta.com/oauth2/default/v1/token
            user-info-uri: https://dev-58841934.okta.com/oauth2/default/v1/userinfo
            jwk-set-uri: https://dev-58841934.okta.com/oauth2/default/v1/keys
        registration:
          okta:
            client-id: 0oa9unhksvONAY2gV5d7
            client-secret: QFPR-lODLJ8kfSyo5bd49cf508SUwVAscOBi106S