services:

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:21.1.1
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "9090:8080"
    command:
      - "start-dev"

  app:
    container_name: app
    image: app
    environment:
      spring.security.oauth2.resourceserver.jwt.issuer-uri: http://keycloak:9090/realms/helloworld-realm
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
