version: "4"
services:

  app:
    image: app-image:0.0.1
    container_name: app-container
    build:
      dockerfile: Dockerfile
    environment:
      stripe.secretKey:
    ports:
      - 8080:8080