version: '3'
 
services:

  mysql:
    image: mysql:5.7
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_password
      MYSQL_DATABASE: database
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s   
    networks:
      - helloworld-network
#    volumes:
#      - dbdata:/var/lib/mysql

  be:
    image: be-image:0.0.1
    container_name: be-container
    build:
      context: ./fe-react-be-springboot-db-sql-mysql_BE
      dockerfile: Dockerfile
    environment:
      spring.datasource.url: jdbc:mysql://mysql:3306/database
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - 8081:8081
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - helloworld-network

  fe:
    image: fe-image:0.0.1
    container_name: fe-container
    build:
      context: ./fe-react-be-springboot-db-sql-mysql_FE
      dockerfile: Dockerfile
    depends_on:
      - be
    ports:
      - 3000:3000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - helloworld-network

networks:
  helloworld-network:
    name: helloworld-network-name