apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: producer
  name: producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
        - image: wisniewskikr/springboot3-kafka-obsidiandynamics-json-model_producer:0.0.1
          name: producer
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: SPRING_KAFKA_PRODUCER_BOOTSTRAP_SERVERS
              value: kafka:29092
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: producer
  name: producer
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    app: producer