version: '3.8'

services:

  be:
    container_name: be
    image: be
    build:
      context: ./angular-springboot-spa-security-keycloak-be
      dockerfile: Dockerfile    
    ports:
      - "8080:8080"

  fe:
    container_name: fe
    image: fe
    build:
      context: ./angular-springboot-spa-security-keycloak-fe
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    restart: always