server:
    port: 8081

api:
  second:
    url: http://localhost:8082/api/v1

keycloak:
  url: http://localhost:8080
  administrator:
    username: user
    password: user

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/helloworld-realm
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs