spring:
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: password

application:
  database: neo4j

logging:
  level:
    org.springframework.data.neo4j: TRACE