version: '3.8'

services:
  
  helloworld-8080:
    image: helloworld-image-8080
    container_name: helloworld-container-8080
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080
  
  helloworld-9090:
    image: helloworld-image-9090
    container_name: helloworld-container-9090
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 9090:8080
  
  redis:
    image: redis:7.0.11-alpine
    container_name: redis-container
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - cache:/data

volumes:
  cache:
    driver: local  