version: '3'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    container_name: elasticsearch-container
    ports:
      - 9200:9200
      - 9300:9300
    environment:
        discovery.type: single-node
        xpack.security.enabled: false
        cluster.name: helloworld-cluster